on:
  push:

jobs:
  matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest 
        - macos-latest-xlarge
    runs-on: ${{ matrix.os }}

    steps:
      - run: uname -a