on:
  push:

jobs:
  matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest 
        - labels: ARM64
    runs-on: ${{ matrix.os }}

    steps:
      - run: uname -a
